# Site
repository: agyaglikci
# favicon: images/favicon.ico

# Personal info
name: Abdullah Giray Yaglikci
title: Research and Teaching Assistant PhD Student
email: giray.yaglikci@inf.ethz.ch
website: agyaglikci.github.io

# Social links
twitter_username: agyaglikci
github_username:  agyaglikci
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: agyaglikci
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD student at [Safari Research Group](https://safari.ethz.ch) at
  ETH Zürich under supervision of [Prof. Onur Mutlu](https://people.inf.ethz.ch/omutlu/).
  I work in the field of computer architecture and particularly I focus on memory
  subsystem.
  My recent research includes the characterization of DRAM devices for energy
  efficient use-cases as well as improving their reliability and security.

# Projects Section
projects_title: Research Papers

# Experience Section
experience_title: Work Experience

# Education Section
educaton_title: Education

# More Section
more_title: More Information About Me
more_content: | # this will include new lines to allow paragraphs
  I'm a citizen of Turkey, residing in Zurich (Switzerland).
  I usually communicate with human-kind in Turkish and English, and with machine-kind
  in Python, C++, and Verilog HDL.

  ## Other Projects
  These are the projects that I have significantly participated in my early career
  (in reverse chronological order).
    - Effect of Computational Resources on Parallel Processing, Adv. Computer Architecture Course, MS
    - Is GPGPU Worth to Effort on Audio Processing Functions, Adv. Operating Systems Course, MS
    - expokent.com and cataload.com B2B Network Models, Self Initiative
    - FPGA Based Real Time Image Rotating, Embedded Systems Course, BS.
    - Autopilot Design for Unmanned Aerial Vehicle, Independent Research, BS.
    - Lagari Model Plane Design, DBF2010 Competition, AIAA

  ## References
  Below is a list of the people whom I have been lucky to work with.

  People from academia:
    - [Dr. Onur Mutlu](https://www.linkedin.com/in/omutlu/) **(PhD advisor)**
    - [Dr. Juan Gomez Luna](https://www.linkedin.com/in/juan-gómez-luna-428b3b12/)
    - [Dr. Saugata Ghose](https://www.linkedin.com/in/sghose/)
    - [Dr. Lois Orosa](https://www.linkedin.com/in/loisorosa/)
    - [Dr. Oguz Ergin](https://www.linkedin.com/in/oguzergin/) (MSc advisor)
    - [Dr. X. Sharon Hu](https://www3.nd.edu/~shu/) and [Dr. Michael Niemier](https://www3.nd.edu/~mniemier/) (MSc advisors)


  People from industry:
    - [Dr. Lavanya Subramanian](https://www.linkedin.com/in/lavanya-subramanian-0098338/) was my mentor @ Intel Labs
    - [Sreenivas Subramoney](https://www.linkedin.com/in/sreenivas-subramoney-i-am-hiring-6564521/) was my supervisor @ Intel Labs
    - [Dr. Kevin K. Chang](https://www.linkedin.com/in/kevin-chang-kaiwei/) was my mentor during my internship @ Carnegie Mellon University
    - [Tuna Caglar Gumus](https://www.linkedin.com/in/tcgumus/) has been my collegue at numerous projects and he was co-founder of both expokent.com and cataload.com


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
