# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Abdullah Giray Yaglikci
title: Research and Teaching Assistant PhD Student
email: giray.yaglikci@inf.ethz.ch
website: agyaglikci.github.io

# Social links
twitter_username: agyaglikci
github_username:  agyaglikci
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: agyaglikci
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a PhD student at [Safari Research Group](https://safari.ethz.ch) at ETH Zürich under supervision of [Prof. Onur Mutlu](https://people.inf.ethz.ch/omutlu/).
  I work in the field of computer architecture and particularly focused on memory subsystem.
  My recent research includes the characterization of DRAM devices for energy efficient use-cases as well as improving DRAM reliability and security.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
